### ISSUE TITLE
clarify _authority public access

### ISSUE THREAD

**Issue by rainbeam** [nexusdev/ds-auth#1]
`_authority` is available as a public accessor, yet it is _ prefixed. This seems contradictory - why not expose without the _?

**Comment by nmushegian** [comment]
artifacts. Changing DSAuthorized breaks everything and needs a major version bump for dappsys. Probably best to address it asap. Another issue is whether to keep using enums or to make "auth mode" back into a bool.

**Comment by dbrock** [comment]
would be nice to have a way to deprecate API:s in a way that it displays a warning when they are used
