### ISSUE TITLE
updated "auth mode" mechanism

### ISSUE THREAD

**Issue by nmushegian** [nexusdev/ds-auth#2]
the auth mode is an enum because I anticipated more auth modes, but that didn't happen. `canCall` is a nice general ACL scheme.

An authority can fully simulate owner mode by returning true for `canCall(authority, target, bytes4(sha3("updateAuthority(bytes4,uint8)"))`

brainstorming `DSAuthorized` changes:
- when in "auth" mode, falls back to msg.sender check
- `enableAuthLookup/disableAuthLookup`, internally `auth_lookup_enabled` instead of enum
- `releaseToAuthority` - direct to auth mode
- `releaseToOwner` - direct to owner mode

**Comment by dbrock** [comment]
I think it should look like this:

```
import "authority.sol";

contract DSAuth2 {
    address      public  owner;
    DSAuthority  public  authority;

    function DSAuth2() {
        owner = msg.sender;
    }

    function setOwner(address newOwner) auth {
        owner = newOwner;
    }

    function setAuthority(DSAuthority newAuthority) auth {
        authority = newAuthority;
    }

    modifier auth {
        if (!isAuthorized()) throw;
        _
    }

    function isAuthorized() internal returns (bool) {
        if (msg.sender == owner) {
            return true;
        } else if (authority == 0) {
            return false;
        } else {
            return authority.canCall(msg.sender, this, msg.sig)
        }
    }
}
```

**Comment by nmushegian** [comment]
looks good. let me ponder a bit

**Comment by nmushegian** [comment]
what do you think of replacing DSAuth and having the old version be `DSAuthLegacy`. I think maker-core is the only live user

**Comment by dbrock** [comment]
I think that's fine. But I also think we should seriously start applying Kelvin versioning. If we call a package `Foo` then we should be able to explain why it's the the be-all and end-all ever `Foo`....?

It should be in the name!
